### ISSUE TITLE
provide analysis of the flutter section of pubspec.yaml files

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#1259]
In particular, we should warn if there are assets referenced that don't exist:

```yaml
flutter:
  uses-material-design: true
  assets:
    - lib/gallery/example_code.dart
    - packages/flutter_gallery_assets/appbar_background.jpg
    - packages/flutter_gallery_assets/appbar/appbar_background_layer0.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer1.png
    - packages/flutter_gallery_assets/appbar/appbar_background_layer2.png
    - packages/flutter_gallery_assets/shrine/vendors/sandra-adams.jpg
    - packages/flutter_gallery_assets/shrine/vendors/zach.jpg
  fonts:
    - family: Raleway
      fonts:
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-Regular.ttf
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: packages/flutter_gallery_assets/pesto/fonts/Raleway-SemiBold.ttf
          weight: 600
    - family: AbrilFatface
      fonts:
        - asset: packages/flutter_gallery_assets/shrine/fonts/abrilfatface/AbrilFatface-Regular.ttf
```

Likely this work would all happen in the analysis server.
