### ISSUE TITLE
Manually deleting library from the External Libraries folder doesn't delete or return

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter-intellij#2184]
_From @branflake2267 on June 14, 2017 4:41_

## Steps to Reproduce
1. select folder in external library
2. delete folder (library)
3. run packages get
4. (note the library didn't delete from module settings libraries)

After I deleted them from the module settings library. 
![screen shot 2017-06-13 at 9 36 50 pm](https://user-images.githubusercontent.com/1326504/27115618-bb7c534c-5080-11e7-9aa0-44585d8fa454.png)

I'm expecting packages get to update the classpath and it it's fixing it. 

```
name: points
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutterfl
  google_sign_in: "^0.0.4"
  firebase_auth: "^0.0.3+1"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true
```

## Logs

```
Brandons-MacBook-Pro:points branflake2267$ flutter packages get
Running "flutter packages get" in points...               
Package firebase_auth has no versions that match >=0.0.3+1 <0.1.0 derived from:
- points depends on version ^0.0.3+1
pub get failed (1)
Brandons-MacBook-Pro:points branflake2267$ flutter analyze
Running "flutter packages get" in points...               
Package firebase_auth has no versions that match >=0.0.3+1 <0.1.0 derived from:
- points depends on version ^0.0.3+1
pub get failed (1)
Brandons-MacBook-Pro:points branflake2267$ 

```

## Flutter Doctor

```
Brandons-MacBook-Pro:points branflake2267$ flutter doctor
[✓] Flutter (on Mac OS X 10.12.5 16F73, locale en-US, channel master)
    • Flutter at /Users/branflake2267/git/flutter
    • Framework revision 9f344b695d (2 hours ago), 2017-06-13 19:17:04 -0700
    • Engine revision 4f5d6fab11
    • Tools Dart version 1.24.0-dev.6.7

[✓] Android toolchain - develop for Android devices (Android SDK 26.0.0)
    • Android SDK at /Users/branflake2267/Library/Android/sdk
    • Platform android-26, build-tools 26.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] iOS toolchain - develop for iOS devices (Xcode 8.3.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 8.3.3, Build version 8E3004b
    • ios-deploy 1.9.1
    • CocoaPods version 1.2.1

[✓] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Gradle version 3.2
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] IntelliJ IDEA Community Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] IntelliJ IDEA Ultimate Edition (version 2017.1.4)
    • Flutter plugin version 14.0
    • Dart plugin version 171.4694.29

[✓] Connected devices
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

```

Note: the libraries are incomplete now: 
![screen shot 2017-06-13 at 9 42 10 pm](https://user-images.githubusercontent.com/1326504/27115691-35beeef8-5081-11e7-9abd-3e392e0b387d.png)

_Copied from original issue: flutter/flutter#10687_
