### ISSUE TITLE
I Can't build a flutter project after add "Path_Provider" dependency, it's a problem....

### ISSUE THREAD

**Issue by Zewe1995** [flutter/flutter-intellij#4296]
Thanks for the feedback! If your issue is related to the Flutter framework itself,
please open an issue at
[github.com/flutter/flutter](https://github.com/flutter/flutter/issues/new).

## Steps to Reproduce

_Please tell us what you were doing and what went wrong_

## Version info

Please paste the output of running `flutter doctor -v` here (available from the command
line or from `Tools > Flutter > Flutter Doctor`). It will provide the version of the
Flutter framework as well as of the IntelliJ plugin.

**Comment by stevemessick** [comment]
We'll need more info to help.

What does this mean: 'add "Path_Provider" dependency'?
What does "can't build" mean?

Give us some screenshots or textual error messages to work with.

Please add the output of `flutter doctor -v`.

**Comment by moslemezzati** [comment]
I have the same problem which shows this error message:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'path_provider'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:3.3.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom
       - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.pom
       - https://jcenter.bintray.com/com/android/tools/build/gradle/3.3.0/gradle-3.3.0.jar
     Required by:
         project :
```
and my dependencies is:
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider: ^1.5.1
```
I need to say that I don't have any issue by running `flutter doctor -v`
```
