### ISSUE TITLE
omit_local_variable_types have been disable but still get warning Omit type annotations for local variables.

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter-intellij#4644]
<img width="339" alt="Screen Shot 2020-06-22 at 4 53 58 PM" src="https://user-images.githubusercontent.com/52562340/85274405-169bbf80-b4a9-11ea-8955-149ebe4ed2d4.png">

<img width="626" alt="Screen Shot 2020-06-22 at 4 54 11 PM" src="https://user-images.githubusercontent.com/52562340/85274426-1e5b6400-b4a9-11ea-9d42-a9bb29f86ccc.png">

I was clicked on `Open documentation` and it show https://dart-lang.github.io/linter/lints/omit_local_variable_types.html

**Comment by pq** [comment]
Hi @tbm98.  Could you share your complete analysis options file?  I'm guessing you're including another set of options (pedantic?) that are enabling this lint.  In that case, you'll  need to **_explicitly disable_** it as described here: https://dart.dev/guides/language/analysis-options#disabling-individual-rules.

**Comment by tbm98** [comment]
complete analysis options
```
include: package:pedantic/analysis_options.yaml
#  - package:effective_dart/analysis_options.1.2.0.yaml
analyzer:
#  strong-mode:
#    implicit-casts: false
#    implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
  exclude:
    - "lib/helpers/viet_calendar.dart"
#    - "bin/cache/**"
    # the following two are relative to the stocks example and the flutter package respectively
    # see https://github.com/dart-lang/sdk/issues/28463
#    - "lib/i18n/messages_*.dart"
#    - "lib/src/http/**"
linter:
  rules:
    # these rules are documented on and in the same order as
    # the Dart Lint rules page to make maintenance easier
    # https://github.com/dart-lang/linter/blob/master/example/all.yaml
    - always_declare_return_types
    - always_put_control_body_on_new_line
#    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
#    - always_specify_types
    - annotate_overrides
#    - avoid_annotating_with_dynamic
    # - avoid_as
    - avoid_bool_literals_in_conditional_expressions
    # - avoid_catches_without_on_clauses
#    - avoid_catching_errors
    - avoid_classes_with_only_static_members
#    - avoid_double_and_int_checks
    - avoid_empty_else
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
#    - avoid_implementing_value_types
    - avoid_init_to_null
#    - avoid_js_rounded_ints
    - avoid_null_checks_in_equality_operators
#    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    #    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    #    - avoid_types_on_closure_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    #    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
#    - cascade_invocations
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - curly_braces_in_flow_control_structures
    # - diagnostic_describe_all_properties
#    - directives_ordering
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - file_names
#    - flutter_style_todos
    - hash_and_equals
    - implementation_imports
    - invariant_booleans
    - iterable_contains_unrelated_type
#    - join_return_with_assignment
    - library_names
    - library_prefixes
#    - lines_longer_than_80_chars
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - non_constant_identifier_names
    - null_closures
    # - omit_local_variable_types
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
#    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
#    - prefer_constructors_over_static_methods
    - prefer_contains
    # - prefer_double_quotes
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    #    - prefer_mixin
    - prefer_null_aware_operators
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    # - public_member_api_docs
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - type_annotate_public_apis
    - type_init_formals
    #    - unawaited_futures
    #    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    # - unnecessary_final
    - unnecessary_getters_setters
    # - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_this
    - unrelated_type_equality_checks
    #    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    #    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
#    - use_setters_to_change_properties
    #    - use_string_buffers
    #    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks
    - avoid_void_async
    # - curly_braces_in_flow_control_structures # not yet tested
    # - diagnostic_describe_all_properties # not yet tested
    - directives_ordering
    # - file_names # not yet tested
#    - flutter_style_todos
    - unnecessary_string_interpolations
```
