### ISSUE TITLE
Add a way to cancel Flutter commands

### ISSUE THREAD

**Issue by pq** [flutter/flutter-intellij#525]
If a command hangs (or appears to hang), we should have a way to cancel it:

<img width="680" alt="screen shot 2016-12-12 at 8 36 48 am" src="https://cloud.githubusercontent.com/assets/67586/21107357/4253e87e-c046-11e6-9b2e-b54dc7d735d5.png">

**Comment by pq** [comment]
Update: while I think the request stands, it looks like my command hadn't hung above but was rather just very quick.  When run from the commandline I see:

```
[~/IdeaProjects/untitled8_901210921] $ flutter packages get
Running 'flutter packages get' in untitled8_901210921... 497ms
```

I wonder if there shouldn't be a better indication that the command has run?

Should we print the time elapsed (as we do on the commandline)?

cc @devoncarew @danrubel

**Comment by devoncarew** [comment]
+1 to printing something in IntelliJ (`flutter packages get finished.` or similar).

**Comment by pq** [comment]
See also: #1923 .

**Comment by IchordeDionysos** [comment]
I had a case where I had something like this in my pubspec.yaml:

```yaml
dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    some_pub:
        git:
           url: git@https://github.com/simpleclub/some_pub.git
           ref: master
```

I know there is an error `git@https://github.com/simpleclub/some_pub.git` should have been `git@github.com/simpleclub/some_pub.git`.

My point is that Flutter tried to fetch the incorrect dependency with exponential backoff and I had no way to stop the command.
