### ISSUE TITLE
Error is not highlighted in Android Studio.

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter-intellij#6062]
Error is not highlighted in Android Studio. How can I solve this?

```
flutter doctor -v
[✓] Flutter (Channel stable, 2.10.4, on macOS 12.3 21E230 darwin-x64, locale
    en-LK)
    • Flutter version 2.10.4 at /Users/bhanukaisuru/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (4 days ago), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/bhanukaisuru/Library/Android/sdk
    • Platform android-32, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.65.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.36.0

[✓] Connected device (2 available)
    • M2012K11AG (mobile) • a812c3db • android-arm64  • Android 12 (API 31)
    • Chrome (web)        • chrome   • web-javascript • Google Chrome 99.0.4844.83

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

![Screenshot 2022-03-28 at 12 22 30 PM](https://user-images.githubusercontent.com/34953062/160342264-8b755028-a0e1-4906-b0f4-13d5c6b61c79.png)
![Screenshot 2022-03-28 at 12 20 04 PM](https://user-images.githubusercontent.com/34953062/160342274-3a231273-7438-4f9f-9ada-758d47044bdb.png)

**Comment by stevemessick** [comment]
I cannot reproduce this. I get the error: Constructors can't have a return type.

Please provide a full example for reproduction. Have you tried restarting the analysis server?

**Comment by bhanuka96** [comment]
Try to create new Flutter project.


This is my `pubspec.yaml`

```
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.4
  dio: ^4.0.5
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  hooks_riverpod: ^1.0.3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  mockito: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

```
