### ISSUE TITLE
Import suggestions list take a couple of tries to show. 

### ISSUE THREAD

**Issue by dark-chocolate** [flutter/flutter-intellij#6388]
## Steps to Reproduce

1. Create any class, say `User`. 
2. Create a new dummy class but in different directory. 
3. Type `User` in the new dummy class. 
4. Try to import the `User` class now (in dummy class)

<img width="289" alt="image" src="https://user-images.githubusercontent.com/40364434/199703370-6b3cd74e-8c0d-4ee6-8d01-d9fa083fa994.png">

After pressing <kbd>option</kbd>  <kbd>+</kbd>   <kbd>return</kbd> couple of times, it shows the import suggestions: 

<img width="568" alt="image" src="https://user-images.githubusercontent.com/40364434/199703454-b508371b-b5b0-421d-a3d9-521366950c21.png">

## Flutter doctor: 

```
[✓] Flutter (Channel master, 3.5.0-10.0.pre.17, on macOS 12.6 21G115 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Community Edition (version 2021.3.2)
[✓] VS Code (version 1.72.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by ArZargaryan** [comment]
The same problem(much bigger) here.
https://github.com/flutter/flutter-intellij/issues/6385

**Comment by stevemessick** [comment]
This is a performance issue in the Dart analyzer. Please create a new issue here: https://github.com/dart-lang/sdk/issues

If you add a link to the issue you create then I'll add the proper labels to bring it to the attention of the analyzer team.

**Comment by dark-chocolate** [comment]
Thanks @stevemessick for creating that issue. Should we close this issue in regards to the new issue you created?

**Comment by stevemessick** [comment]
Yes. I'll close it in a day or two. Just letting it ride in case others are having a similar problem.

**Comment by srawlins** [comment]
@dark-chocolate  thanks for filing an issue! Can you indicate whether you have any analyzer plugins in play? These would likely be in `analysis_options.yaml` for one or more packages in your project. Examples include "Flutter Enhancement Suite plugin" and "Dart Code Metrics".

**Comment by dark-chocolate** [comment]
@srawlins 

I have the preinstalled `flutter_lints` and I've modified some linter rules myself. 

```
include: package:flutter_lints/flutter.yaml

linter:
  rules:
     avoid_print: false
     unawaited_futures: true
     use_super_parameters: true
     prefer_const_constructors: false
     use_key_in_widget_constructors: false
     prefer_const_literals_to_create_immutables: false
     prefer_const_constructors_in_immutables: false
     prefer_relative_imports: true
     unnecessary_lambdas: true
     avoid_catches_without_on_clauses: true
     avoid_catching_errors: true
     avoid_classes_with_only_static_members: true
     prefer_mixin: true
     use_setters_to_change_properties: true
     avoid_setters_without_getters: true
     type_annotate_public_apis: true
     avoid_types_on_closure_parameters: true
     avoid_positional_boolean_parameters: true
     avoid_slow_async_io: true
```
